apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subjectaccessreviews
  namespace: {{ .Release.Namespace }}
subjects:
- kind: User
  name: system:serviceaccount:validate-secrets:validate-secrets
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: subjectaccessreviews
  apiGroup: rbac.authorization.k8s.io
