apiVersion: v1
kind: Secret
metadata:
  name: validate-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  key.pem: "{{ .Values.webhook.servingKey | b64enc }}"
  cert.pem: "{{ .Values.webhook.servingCert | b64enc }}"
